### PR TITLE
style: replaced unipilot with a51 finance

### PR DESCRIPTION
**Pull request by anshss**

### CODE REVIEW

**Review by totop716 — CHANGES_REQUESTED** [review]
src/pages/SwapPage/SwapPage.tsx
  Line 103:25:  Insert `⏎`  prettier/prettier

Please fix this lint error.

**Review by totop716 — CHANGES_REQUESTED** [review]
https://github.com/QuickSwap/interface-v2/blob/170e87cca320448f9cfc107731efc30bb59f24c7/src/hooks/v3/useUnipilotFarms.ts#L411

Replace unipilot with a51 finance here

**Review by totop716 — CHANGES_REQUESTED** [review]
https://github.com/QuickSwap/interface-v2/blob/dev2/src/utils/index.ts

Replace unipilot with a51 finance in the error messages here

**Comment by anshss** [comment]
I have made the above changes

**Review by totop716 — APPROVED** [review]

**Review by sameepsi — APPROVED** [review]

**Pull request merged**
