### PR TITLE
Fix audit issues

### PR DESCRIPTION
**Pull request by totop716**

### CODE REVIEW

**Review by FriskyHamTitz — APPROVED** [review]

**Comment by FriskyHamTitz** [comment]
We should have the auditors review the react rewired scripts

**Review by AKsphere — COMMENTED** [review]
I honestly just started learning code. So I don't understand the meaning of this content. But I'm hoping it's debugging and fixing issues in my accounts.

**Comment by AKsphere** [comment]
I appreciate the work you're doing and looking forward to becoming proficient in coding in the near future.

**Comment by sameepsi** [comment]
@FriskyHamTitz What's the update here?

**Review by AKsphere — APPROVED** [review]

**Review by FriskyHamTitz — COMMENTED** [review]
Hmm, I see you swapped to use react-scripts-rewired but do we actually need that I don't see the bump to react 5 here?

**Comment by totop716** [comment]
> @FriskyHamTitz What's the update here?

This is to fix audit errors for security showing when running `yarn audit`

**Review by sameepsi — APPROVED** [review]

**Pull request merged**
