### PR TITLE
[Feature] Add Tally Ho Wallet

### PR DESCRIPTION
**Pull request by 0xzoz**
Add [Tally Ho](https://tally.cash/) as a wallet option. Tally Ho is a community-built browser extension and has just enabled Polygon support. There will be an announcement in the following weeks

This PR includes:

- Tally as a wallet option when connecting

Functionality:

- CASE: Both Metamask and Tally installed but Tally not set as default
  - Tally shows error when clicked to either download or set to default
- CASE: Only Metamask installed
  - Tally shows error when clicked to either download or set to default
- CASE: Only Tally installed
  - Metamask will not show
- CASE: Metamask and Tally installed. Tally set as default
  - Metamask will not show.

### CODE REVIEW

**Comment by RitzyDevBox** [comment]
If you would like wallet integration into the site, you need to contact the Business Development Team first. 
You can reach them through telegram

**Comment by Naxsun** [comment]
Thanks for the fast response. We're in contact with Darren! 👍

**Comment by Naxsun** [comment]
Is there anything we can do from or side on this?

**Comment by RitzyDevBox** [comment]
@Naxsun what's the status of the BD chat I haven't heard anything from you guys since then?

**Comment by Naxsun** [comment]
Hi @RitzyDevBox I was in contact with Darren but after providing some information and inviting Quickswap over to one of our community calls I haven't gotten a response.

Is there any other BD contact I could reach out too?

**Comment by RitzyDevBox** [comment]
Dm him again and ask to add ritzy to the chat

**Comment by Naxsun** [comment]
Hey @RitzyDevBox asked him but no response so far

**Pull request closed without merging**
