### PR TITLE
Add new tokens, syrups, farms and token icons

### PR DESCRIPTION
**Pull request by totop716**

### CODE REVIEW

**Review by sameepsi — APPROVED** [review]
Looks good to me

**Review by FriskyHamTitz — COMMENTED** [review]
Why are there that many changes to syrup? I can't read this

**Review by FriskyHamTitz — CHANGES_REQUESTED** [review]
Way too many changes to stake.json please fix commit

**Review by FriskyHamTitz — APPROVED** [review]

**Comment by FriskyHamTitz** [comment]
Sameep reviewed all the missing LPs and said they're approved.  We need to move this list into an npm package

**Pull request merged**
