### PR TITLE
Add dappos menu item to header and fix social menu bar

### PR DESCRIPTION
**Pull request by webdev403**

### CODE REVIEW

**Comment by webdev403** [comment]
[Add DappOS to partners dropdown](https://trello.com/c/iHIZk15w/457-add-dappos-to-partners-dropdown)

**Comment by webdev403** [comment]
[Remove Medium from available social lists](https://trello.com/c/l4hMfTJK/448-remove-medium-from-available-social-lists)

**Comment by webdev403** [comment]
[Fix Social buttons on homepage](https://trello.com/c/Mpt74IOX/455-fix-social-buttons-on-homepage)

**Comment by webdev403** [comment]
[Adjust colors for stats page](https://trello.com/c/JMYzDF2h/454-adjust-colors-for-stats-page)

**Review by sameepsi — APPROVED** [review]

**Review by sameepsi — APPROVED** [review]

**Pull request merged**
